apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: peerprep-user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP  # Use 'NodePort' if you want to expose the service externally