apiVersion: v1
kind: Service
metadata:
  name: question-service
  namespace: peerprep-question-service
spec:
  selector:
    app: question-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP  # Use 'NodePort' if you want to expose the service externally