apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: peerprep-frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 30
      targetPort: 3000  
      nodePort: 30000
  type: LoadBalancer  # Use 'NodePort' if you want to expose the service externally