apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: peerprep-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: asia-southeast1-docker.pkg.dev/cs3219-project-g22/peerprep-docker/frontend:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: frontend-configmap
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"