apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-service
  namespace: peerprep-matching-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-service
  template:
    metadata:
      labels:
        app: matching-service
    spec:
      containers:
      - name: matching-service
        image: cpauzi/matching-service:latest
        ports:
          - containerPort: 8081
        envFrom:
        - configMapRef:
            name: matching-service-configmap
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"