apiVersion: v1
kind: ConfigMap
metadata:
  name: matching-service-config-elqj
  namespace: peerprep-matching-service
data:
  KAFKA_BROKERS: "kafka:9092"
  KAFKA_TOPIC: "matching-requests,matching-results,match-canceled,match-timeout,match-rejected,match-accepted,collab-request"
