apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: default
spec:
  ports:
    - port: 2181
      name: client
  clusterIP: None  # Headless service for stable network identity
  selector:
    app: zookeeper